name: Docker React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t htmmzk/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true htmmzk/docker-react npm run test